# Generated by Django 5.2.3 on 2025-06-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_fee",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Daily rental fee in $USD",
                        max_digits=5,
                    ),
                ),
                (
                    "inventory",
                    models.PositiveIntegerField(
                        help_text="Number of available copies of this book in the library"
                    ),
                ),
                (
                    "cover",
                    models.CharField(
                        choices=[("HARD", "Hardcover"), ("SOFT", "Softcover")],
                        default="HARD",
                        max_length=10,
                    ),
                ),
                ("author", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
            ],
        ),
    ]
