# Generated by Django 5.2.3 on 2025-06-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_username_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255, null=True, verbose_name="username"),
        ),
    ]
